### ISSUE TITLE
Plugins busted?

### ISSUE THREAD

**Issue by eddelbuettel** [dcdillon/RcppHoney#16]
I was just looking at this in light of your open and unanswered [Rcpp issue #522](https://github.com/RcppCore/Rcpp/issues/522).

Pulling and installing RcppHoney leads to this:

``` r
R> library(Rcpp)
R> library(RcppHoney)
R> ls(Rcpp:::.plugins)
[1] "cpp0x"     "cpp11"     "cpp14"     "cpp1y"     "openmp"    "RcppHoney"
R> Rcpp:::.plugins[["RcppHoney"]]
function (...) 
{
    includes <- sprintf("%s\n#include <Rcpp.h>\n%s\n\n#ifndef BEGIN_RCPP\n#define BEGIN_RCPP\n#endif\n\n#ifndef END_RCPP\n#define END_RCPP\n#endif\n\nusing namespace Rcpp;\n", 
        include.before, include.after)
    out <- list(env = list(PKG_LIBS = libs), includes = includes, 
        LinkingTo = LinkingTo, body = function(x) {
            sprintf("BEGIN_RCPP\n%s\nEND_RCPP", x)
        }, Depends = Depends)
    if (!is.null(Makevars)) 
        out$Makevars <- Makevars
    if (!is.null(Makevars.win)) 
        out$Makevars.win <- Makevars.win
    out
}
<environment: 0x120b340>
R> 
```

I don't think that is what we want.  Compare eg to

``` r
R> Rcpp:::.plugins[["openmp"]]
function () 
{
    list(env = list(PKG_CXXFLAGS = "-fopenmp", PKG_LIBS = "-fopenmp"))
}
<environment: namespace:Rcpp>
R> Rcpp:::.plugins[["cpp14"]]
function () 
{
    list(env = list(PKG_CXXFLAGS = "-std=c++14"))
}
<environment: namespace:Rcpp>
R> 
```

I may of course just be misunderstanding something.  Doing a simple function like

``` c++
#include <Rcpp.h>

using namespace Rcpp;

// [[Rcpp::plugins(RcppHoney)]]

// [[Rcpp::export]]
double sumTwo(double a, double b) {
  return a+b;
}
```

with an without the plugin _does_ result in two differently sized .so files so that works.

How about also renaming the plugin no after the package it is but after the functionality it offers?

**Comment by eddelbuettel** [comment]
If you search GitHub for `Rcpp.plugin.maker` you get  [e.g. all this](https://github.com/search?q=Rcpp.plugin.maker&type=Code&utf8=%E2%9C%93).  The use by KK in RcppMLPACK looks clean:

``` r
inlineCxxPlugin <- function(...) {
    plugin <- Rcpp::Rcpp.plugin.maker(
        include.before = "#include <RcppMLPACK.h>", 
        libs = sprintf("%s $(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS)", RcppMLPACKLdFlags()),
        LinkingTo      = c("RcppArmadillo", "Rcpp", "BH", "RcppMLPACK"),
        package        = "RcppMLPACK"
    )
    settings <- plugin()
    settings
}
```

and see file `R/flags.R` for the rest.  I think you just need to append to `libs` and be done.

**Comment by dcdillon** [comment]
Let me poke around.  Apparently I got something not quite right

**Comment by eddelbuettel** [comment]
I am poking too.  This has to do with functions and function-generator functions.  I think you just skipped a level.  Easy to [just search at GitHub for `inlineCxxPlugin`](https://github.com/search?q=inlineCxxPlugin&type=Code&utf8=%E2%9C%93)

**Comment by eddelbuettel** [comment]
And we took this from the [inline](https://cloud.r-project.org/web/packages/inline/index.html) package so documented tends to be [over there](http://www.rdocumentation.org/packages/inline/versions/0.3.14/topics/plugins).
