### ISSUE TITLE
Testing...and lots of it.  Let's get to beta!

### ISSUE THREAD

**Issue by dcdillon** [dcdillon/RcppHoney#7]
- [x] Create actual unit testing framework with `runit`
- [ ] Create some actual documentation (I'm open to suggestions here as most of the code is - generated by macros, so `roxygen` etc. will be of little use)
- [x] [travis](https://travis-ci.org) hooks
- [x] Create an [rcpp-gallery](http://gallery.rcpp.org) article
- [ ] ~~PROFIT~~

**Comment by dcdillon** [comment]
@coatless - just fyi I invited you because I thought you might be interested.  Let me know.

**Comment by coatless** [comment]
@dcdillon definitely interesting. Very impressed with the initial example. Do you need my help with the list above? 

Also why `RUnit` instead of `testthat`?

**Comment by dcdillon** [comment]
I'm working on travis right now.  I need help with the rest.

As to the `RUnit` vs. `testthat`, I plan to hand the project over to @RcppCore if it gains any traction so I wanted to follow their pattern.

**Comment by coatless** [comment]
For travis, I'd recommend using:

``` bash
# Use the R testing scheme
language: r

# Test on multiple versions (note requirement of R > 3.0)
r:
  - oldrel
  - release
  - devel

# Enable package cache
cache: packages

# Disable sudo to ensure container infrasturcture
sudo: false

# To CRAN, warnings **are** errors.
warnings_are_errors: true

# Build on OS
os:
  - linux
  - osx

notifications:
  email:
    on_success: change
    on_failure: change
```

**Comment by eddelbuettel** [comment]
And Dirk doesn't do testthat or devtools because I am on old grumpy man who wants the kids to get off his lawn...

Truth be told I said to Dan to look at both sides, but I simply know RUnit better.  It works for me. Your (his) mileage may vary, of course.

**Comment by eddelbuettel** [comment]
Too late. I already sent him my `.travis.yml` via Slack.

**Comment by dcdillon** [comment]
Heh...I'm easy on the whole thing, but continuity within an organization seems reasonable to me.

**Comment by dcdillon** [comment]
I can be bribed for one MegaCheeseburger and Fries from Murphy's.

**Comment by coatless** [comment]
Slack? Mmm interesting comm platform. 

@dcdillon let me know when you are down in UC.

**Comment by eddelbuettel** [comment]
We may try Wercker or another CI to 'bring our own containers' or if @coatless doesn't stop whining switch to 'travis v2.0' for Rcpp.  Or not.

**Comment by eddelbuettel** [comment]
We have an informal Slack for Rcpp but it's mostly Dan and myself :)

**Comment by coatless** [comment]
But, but... Think of the testing! 

I dislike Wercker because I have to give it access to everything... Travis is slightly better permission wise. Plus, I get free private builds under the **education** bundle.

**Comment by eddelbuettel** [comment]
You saw my counter example this morning, right?  Two simple Docker calls.  Cheap if you happen to work on the OS that makes Docker _really_ cheap.

**Comment by eddelbuettel** [comment]
Wercker perms are clearly a turn-off.  But GitLab also allows 'bring your own container'.

**Comment by eddelbuettel** [comment]
And yes, the three of us are due some sort of liquid nourishment at some point in the (hopefully near) future.

**Comment by coatless** [comment]
@eddelbuettel

To be honest, I haven't been able to carve out time to really learn and understand docker deployments. I've only briefly touched on them when I helped to get a hadoop to rstudio container with persistent storage active this past year on a VM farm. (I know, I should be knowledgeable... But... ) 

Normal deployments are to:
- EC2
- Private server (c.f. https://rstudio.stat.illinois.edu

I'll dig a bit deeper into it and try to work out a solution. One of the nice things is that https://semaphoreci.com/ does allow for docker based builds. 

Plus, I'm not sure a move to `gitlab` is advisable as a large chunk of the _R_ ecosystem is on github.

**Comment by coatless** [comment]
@eddelbuettel also, feel free to add me to slack group via the balamut2 .... illinois ... edu

**Comment by eddelbuettel** [comment]
if we both happen to be online, awake and sober I'll screen share what I did with you. It is trivially easy and the use against different build environments is _ideally_ suited to tested against old versions....

**Comment by dcdillon** [comment]
OK.  I give up on `.travis.yml`

It seems like no matter what I do with it it tries to run `./configure && make && make test` which isn't quite right.  I'm hacking now.  If someone knows better, that'd be great.

**Comment by coatless** [comment]
@dcdillon Use the travis v2.0 config. **nods**

**Comment by dcdillon** [comment]
I have one last gasp in me...then I might consider it.  And since Dirk is on the train and unavailable....

**Comment by coatless** [comment]
Excellent... Come to the dark side of unit testing... We have cookies!

**Comment by dcdillon** [comment]
Hah!  got the old version to work.  Though I'm not opposed to the new if you'd like to give it a try.  I just changed it to:

```
script:
 - true
```

Since the package install is done before that in the example @eddelbuettel gave me and I don't yet have tests.

**Comment by dcdillon** [comment]
Accept your invite to Rcpp slack so we don't have to clutter the message boards ;)

**Comment by coatless** [comment]
@dcdillon I'm pretty sure I'm in the slack channel for Rcpp  now.

**Comment by eddelbuettel** [comment]
Now https://travis-ci.org/dcdillon/RcppHoney looks good to me as far as the _outcome_ goes but 

> `./travis-tool.sh install_github dcdillon/RcppHoney`

is just wrong -- that's self referential.  You only need Rcpp, and _of course_ the repo that the Travis setup belongs to.  And what I sent you does that.

Anyhow.  Dinner time here.

**Comment by dcdillon** [comment]
Almost done.  I suppose the last step is to create some vignettes or somesuch.  I've never done this before, but my thought is to take the [gallery article](http://gallery.rcpp.org/articles/rcpp-honey/) as a starting point and go from there?

Any advice, etc?

**Comment by eddelbuettel** [comment]
Vignette: two choice are latex (older school, heavier depends, nicer (?) pdf--and these days markdown as a higher-level)) or markdown-to-html.   I have some markdown vignettes in some newer/smaller packages.  See eg drat.  It may be "good enough".  Mostly a question of how _you_ prefer to read / what you prefer to set up.

**Comment by coatless** [comment]
I'm of the newfangled _markdown_ way as it is quicker to write and the threshold for modification contributions is a bit lower.  Plus, the gallery article is done via `.Rmd` so you would have to port what is already written into LaTeX if you proceed with the other way.

Anyhow, to enable the markdown way:

Add a folder called `vignettes` and place the `rcpp-honey.Rmd` inside

Change the upper YML to be:

```
---
title: "RcppHoney Introduction"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{RcppHoney Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```

Add to your `DESCRIPTION` file:

```
Suggests: 
    knitr,
    rmarkdown
```

And you're done!

**Comment by dcdillon** [comment]
Easy enough.  I'm partial to markdown as it's "easy" so will probably go that route.

**Comment by eddelbuettel** [comment]
Yes, markdown is easy and doesn't cause indigestion.   Better still ignore all those "long tutorials" like the one above in @coatless 's post --- and just RStudio.  You may need the rticles (no typo) package from CRAN, or may need a recent-enough RStudio - but 'package vignette' or some such is now a type of Markdown document.  Just try ...

**Comment by coatless** [comment]
What!? Long... Psh. 

In all seriousness, via RStudio:

File -> New File -> New R Markdown ->  From Template -> Package Vignette 

Though the other points about `/vignette` and imports remain.

**Comment by eddelbuettel** [comment]
Yes. Pretty much what I had in mind but I don't have time to think anymore as I have to answer a post by @dcdillon every 7.3 seconds.   Note, though, that some of the formats result in either something semi-ugly, or in something well in excess of a 100kb even for a five-liner.   Still has issues, but I hide now under the rock I placed here perfectly thanks to some algorithms by Knuth himself...
